<?php
    function greeting_menu() {
        $items = array();
        $items['hello_friend'] = array(
            'title' => 'Hey There',
            'page callback' => 'say_hello',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        $items['farewell'] = array(
            'title' => 'Buh Bye',
            'page callback' => 'say_farewell',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function say_hello() {
        return '<p>Hello, my special little friend</p>';
    }
    function say_farewell() {
        return '<p>See you later, sucker!</p>';
    }
    function greeting_user_login() {
        $_GET['destination'] = 'hello_friend';
    }
    function greeting_user_logout() {
        $_GET['destination'] = 'farewell';
    }
