<?php
    function greeting_menu() {
        $items = array();
        $items['hello_friend'] = array(
            'title' => 'Hey There',
            'page callback' => 'say_hello',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );

        $items['farewell'] = array(
            'title' => 'Buh Bye',
            'page callback' => 'say_farewell',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function say_hello(){
        $user_level = $GLOBALS['user']->roles;
        user_cookie_save(array($GLOBALS['user']->name));
        if(isset($user_level[3])) {
            return '<p>Welcome to the Admin view!</p>';
        } elseif (isset($user_level[2])) {
            return '<p>Nice to see you!</p>';
        }
    }

    // function say_farewell() {
    //     return '<p>See you later, ' . $_COOKIE["Drupal_visitor_0"] . '!</p>';
    // }

    //'admin' REFERS TO USER, NOT ROLE. WE ARE MID-ATTEMPT AT TARGETING THE ROLE, NOT THE USERNAME. 
    function say_farewell() {
        if ($_COOKIE["Drupal_visitor_0"] == 'admin') {
            return '<p>Bye bye bye!</p>';
        } else {
            return "<p>Backstreet's Back!</p>";
        }
    }


    function greeting_user_login() {
        $_GET['destination'] = 'hello_friend';
    }

    function greeting_user_logout() {
        $_GET['destination'] = 'farewell';
    }
